

sonar.projectKey=Joseph_Cose_t1
sonar.projectName=Joseph_Cose_t1
sonar.projectVersion=1.0

sonar.host.url=https://sonarqube.ingsoftware.lat/

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.python.version=3.11

sonar.exclusions=\
    **/__pycache__/**,\
    **/*.pyc,\
    .venv/**,\
    venv/**,\
    ejemplos/**,\
    docs/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=\
    **/__init__.py,\
    src/rewards/apps/productor_restaurante.py,\
    src/rewards/apps/consumidor_recompensas.py
